export const DASHBOARD_MOCK = {
  engineeringScore: {
    value: 86,
    trend: "+8%",
    status: "Excellent",
  },
  kpis: [
    {
      id: "delivery-health",
      title: "Delivery Health",
      value: "92%",
      status: "healthy" as const,
      statusLabel: "Healthy",
      trend: "up" as const,
      trendLabel: "+12% vs last month",
      chartColor: "var(--chart-1)",
      sparkline: [62, 68, 71, 75, 80, 86, 92],
    },
    {
      id: "productivity",
      title: "Engineering Productivity",
      value: "84%",
      status: "on-track" as const,
      statusLabel: "On Track",
      trend: "up" as const,
      trendLabel: "+7% vs last month",
      chartColor: "var(--chart-2)",
      sparkline: [58, 64, 67, 72, 76, 80, 84],
    },
    {
      id: "utilization",
      title: "Resource Utilization",
      value: "81%",
      status: "neutral" as const,
      statusLabel: "Stable",
      trend: "down" as const,
      trendLabel: "-3% vs last month",
      chartColor: "var(--chart-3)",
      sparkline: [88, 86, 85, 84, 83, 82, 81],
    },
    {
      id: "risk",
      title: "Delivery Risk",
      value: "3",
      status: "attention" as const,
      statusLabel: "Monitor",
      trend: "neutral" as const,
      trendLabel: "→ open risks",
      chartColor: "var(--destructive)",
      sparkline: [5, 4, 4, 3, 4, 3, 3],
      valueClassName: "text-destructive",
    },
  ],
  deliveryTrend: {
    title: "Delivery Trend",
    description: "Stories and subtasks completed over time",
    dropdown: "Stories",
    data: [
      { month: "Jan", value: 28 },
      { month: "Feb", value: 34 },
      { month: "Mar", value: 31 },
      { month: "Apr", value: 38 },
      { month: "May", value: 42 },
      { month: "Jun", value: 45 },
      { month: "Jul", value: 48 },
    ],
  },
  productivityTrend: {
    title: "Productivity Trend",
    description: "Output relative to engineering capacity",
    dropdown: "Productivity",
    data: [
      { month: "Jan", value: 72 },
      { month: "Feb", value: 74 },
      { month: "Mar", value: 76 },
      { month: "Apr", value: 78 },
      { month: "May", value: 80 },
      { month: "Jun", value: 82 },
      { month: "Jul", value: 84 },
    ],
  },
  technologies: [
    {
      id: "magento",
      name: "Magento",
      status: "healthy" as const,
      statusLabel: "Healthy",
      developers: 8,
      hours: 312,
      stories: 42,
      sparkline: [30, 34, 36, 38, 40, 41, 42],
      chartColor: "var(--chart-1)",
    },
    {
      id: "react",
      name: "React JS",
      status: "healthy" as const,
      statusLabel: "Healthy",
      developers: 5,
      hours: 248,
      stories: 36,
      sparkline: [24, 26, 28, 30, 32, 34, 36],
      chartColor: "var(--chart-2)",
    },
    {
      id: "html",
      name: "HTML",
      status: "attention" as const,
      statusLabel: "Monitor",
      developers: 3,
      hours: 116,
      stories: 22,
      sparkline: [26, 24, 23, 22, 22, 21, 22],
      chartColor: "var(--chart-4)",
    },
    {
      id: "dt",
      name: "DT",
      status: "healthy" as const,
      statusLabel: "Healthy",
      developers: 2,
      hours: 98,
      stories: 18,
      sparkline: [12, 13, 14, 15, 16, 17, 18],
      chartColor: "var(--chart-3)",
    },
  ],
  contributors: [
    {
      name: "Ravi Soni",
      initials: "RS",
      stories: 18,
      storiesMax: 18,
      hours: 96,
      hoursMax: 96,
      efficiency: 94,
    },
    {
      name: "Gaurav Shah",
      initials: "GS",
      stories: 16,
      storiesMax: 18,
      hours: 88,
      hoursMax: 96,
      efficiency: 91,
    },
    {
      name: "Pratik Shah",
      initials: "PS",
      stories: 14,
      storiesMax: 18,
      hours: 82,
      hoursMax: 96,
      efficiency: 88,
    },
    {
      name: "Nainshi Shah",
      initials: "NS",
      stories: 12,
      storiesMax: 18,
      hours: 76,
      hoursMax: 96,
      efficiency: 85,
    },
    {
      name: "Priyanka Mehta",
      initials: "PM",
      stories: 11,
      storiesMax: 18,
      hours: 72,
      hoursMax: 96,
      efficiency: 83,
    },
  ],
  briefItems: [
    {
      id: "1",
      title: "Review delivery risk in active sprints",
      description:
        "Identify teams with blocked work or rising cycle time before end of month.",
      tone: "success" as const,
    },
    {
      id: "2",
      title: "Check utilization across React and Magento",
      description:
        "Balance workload before new commitments are added to the pipeline.",
      tone: "warning" as const,
    },
    {
      id: "3",
      title: "Celebrate top contributors",
      description:
        "Recognize consistent delivery and estimate accuracy in this period.",
      tone: "info" as const,
    },
  ],
} as const;
